spring:
  application:
    name: deepsearch-tools
  ai:
    mcp:
      server:
        enabled: true
        name: deepsearch-tools
        version: 0.0.1
        type: sync
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp
app:
  yandex:
    api:
      token: ${YANDEX_TOKEN}